feat: Add `await` option to both api and cli
RyanZim/EJS-Lint pull request #82
Opened 2020-10-08 14:58 UTC by daedal-knickerbockers

- When `--await` / `await` option is set, templates with `await` will validate

Based on issue https://github.com/RyanZim/EJS-Lint/issues/81

2020-10-08 15:24 UTC, daedal-knickerbockers commented
Hm, I can't seem to get the cli tests run under windows which makes debugging the current issue difficult. Will fix this once I get the tests running.

2020-10-09 06:53 UTC, daedal-knickerbockers commented
@RyanZim Seems to be all good now - could you check if it's okay this way?

2020-10-09 20:58 UTC, RyanZim requested changes
One tiny nitpick; other than that, LGTM.

2020-10-09 20:58 UTC, RyanZim commented on index.js
> +    allowAwaitOutsideFunction: opts.await || false,
Can just cast to boolean here.
```suggestion
    allowAwaitOutsideFunction: !!opts.await,
```

2020-10-14 07:58 UTC, daedal-knickerbockers commented
Sure, change is commited :-)

2020-10-14 13:34 UTC, RyanZim approved these changes
LGTM, thanks for including tests!

2020-10-14 13:35 UTC, merged